### ISSUE TITLE
Doesn't escape Powershell variable properly ($)

### ISSUE THREAD

**Issue by techthoughts2** [VincentKos/vscode-snippet-creator#12]
Steps to reproduce
------------------
Create a snippet from the following PowerShell code block:

```powershell
$getContentSplat = @{
    Exclude = "*.txt"
    Path = 'C:\rs-pkgs'
}
Get-Content @getContentSplat
```

Expected behavior
-----------------
```json
"name": {
    "prefix": "prefix",
    "body": [
        "\\$getContentSplat = @{",
        "    Exclude = \"*.txt\"",
        "    Path = 'C:\\rs-pkgs'",
        "}",
        "Get-Content @getContentSplat"
    ],
    "description": "descr"
}
```
Actual behavior
---------------
```json
"name": {
    "prefix": "prefix",
    "body": [
        "$getContentSplat = @{",
        "    Exclude = \"*.txt\"",
        "    Path = 'C:\\rs-pkgs'",
        "}",
        "Get-Content @getContentSplat"
    ],
    "description": "descr"
}
```

*Note the lack of escaped **$***

## Suggested Fix

There are several ways this can be solved. Here is one proposed solution:

```typescript
buildBody (code: string) {
    //this._body = code.replace(/\t/g, '\\t').replace(/\r/g, '').split("\n");
    if (this._language === 'powershell') {
        var re = /\$/g;
        this._body = code.replace(/\t/g, '\\t').replace(/\r/g, '').replace(re, '\\$').split("\n");
    }
    else {
        this._body = code.replace(/\t/g, '\\t').replace(/\r/g, '').split("\n");
    }
}
```

**Comment by VincentKos** [comment]
It's not a bug it's an expected behavior. 

The `$` symbol is used to define placeholder in your snippet and if we escape them you will need to manually edit the file to add them. 

If you want to use the `$` symbol in your snippet you should escape it manually when you create the snippet.

**Comment by techthoughts2** [comment]
@VincentKos - I appreciate your thoughts on the matter - but that leaves PowerShell folks high and dry for using this extension. A snippet in PowerShell might contain hundreds of $. It's not very practical to go manually escape them all.

The suggestion I posted above would allow all other languages to continue operating as normal, while still providing escaped $ for PowerShell users. In PowerShell, $ is used quite frequently.

Let me know your thoughts.
