### ISSUE TITLE
Newline added to snippet body

### ISSUE THREAD

**Issue by RobDesideri** [VincentKos/vscode-snippet-creator#3]
Snippets generated by the extension includes the new line escape sequence (`\r` or `\n`) for every body item.

For example, this is a real snippet generated:

```json
"fun": {
  "prefix": "fun",
  "body": [
    "function FunctionName () {\r",
    "  Write-Host \r",
    "}"
  ],
  "description": "generic function"
},
```

As for VSCode documentation, every body array item [is already a new line](https://code.visualstudio.com/docs/editor/userdefinedsnippets#_creating-your-own-snippets).

So, the new line symbol should be removed.

**Comment by VincentKos** [comment]
Can you give some info about your settings and os please ? I guess the problem is windows only. If you add ` "files.eol": "LF"` to your settings it is fixed ?

I'll fix this soon.

**Comment by RobDesideri** [comment]
Environment: Windows 10 64 bit; VSCode 1.30.

Yes, you're right, the problem **only** occurs with the new line set in `CRLF`.
If I set the `LF` EOL, everything works as expected.

**Comment by VincentKos** [comment]
fixed
