### ISSUE TITLE
Automatic fetch language

### ISSUE THREAD

**Issue by NavjotSingh007** [VincentKos/vscode-snippet-creator#4]
Feature Wanted !!!
When creating a snippet using your extension, If it could automatically get the current using language in the input box rather than only showing current language as a placeholder will be really cool.
Referencing extension.js line 27

**Comment by VincentKos** [comment]
Nice idea. I don't have much time but I'd accept a PR that add this.

**Comment by VincentKos** [comment]
Feature added in commit c375f640219df37707117fad7276799547939e64
